#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; pwd -P )"
SCRIPT_PATH=${SCRIPT_PATH}/..

QEMU="${SCRIPT_PATH}/qemu/build/qemu-system-x86_64"
QEMU_IMG="${SCRIPT_PATH}/qemu/build/qemu-img"
QEMU_MONITOR_PORT="56017"

# Port Forward
export SSH_PORT=4444

# CVM parameters
IGVM="${SCRIPT_PATH}/svsm/bin/coconut-qemu.igvm"
CVM_IMAGE="${SCRIPT_PATH}/cvm-imgs/v3-20260715/vtpm-disk-resized.qcow2"
TPM_STATE="${SCRIPT_PATH}/cvm-imgs/v3-20260715/vtpm-state.raw"
CVM_LUKS_PASSPHRASE="MY-LUKS-PASSPHRASE"

# Guest image configuration
DEFAULT_DISTRO=f42
declare -A INSTALLER_URLS=(
  [t42]="http://mirrors.cloud.tencent.com/fedora/releases/42/Server/x86_64/os/"
  [f42]="https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Server/x86_64/os/"
  [c10s]="http://mirror.us.mirhosting.net/centos/10-stream/BaseOS/x86_64/os/"
)

# SVSM proxy configuration
PROXY_SOCK="${SCRIPT_PATH}/lawson-scripts/svsm-proxy.sock"

# KBS
KBS_URL="http://192.168.6.115:50000"
KBS_PID="${SCRIPT_PATH}/kbs/kbs.pid"
KBS_MEASUREMENT="${SCRIPT_PATH}/kbs/kbs.measurement"
KBS_SECRET="${SCRIPT_PATH}/kbs/kbs.secret"
